services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: desenrola_web
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      # ðŸš« NÃƒO monte .next como volume!
      # - nextjs-cache:/app/.next
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - NEXT_TELEMETRY_DISABLED=1
      - FAST_REFRESH=true
    command: ["npm", "run", "dev"]

volumes: {}
